# Generated by Django 4.0.6 on 2022-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_busadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_routeadmin',
            field=models.BooleanField(default=False),
        ),
    ]
