# Generated by Django 4.0.6 on 2022-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=255, null=True),
        ),
    ]
