# Generated by Django 4.0.6 on 2022-08-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0009_alter_subroute_bus'),
        ('customer', '0003_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destnation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_admin.subroute'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_begin_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_admin.single_bus'),
        ),
    ]
