# Generated by Django 4.0.6 on 2022-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0010_seat'),
        ('customer', '0006_alter_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(null=True, to='bus_admin.seat'),
        ),
    ]
