# Generated by Django 4.0.6 on 2022-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0011_rename_umber_of_seats_single_bus_number_of_seats'),
        ('customer', '0009_alter_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(null=True, to='bus_admin.seat'),
        ),
    ]
