# Generated by Django 4.0.6 on 2022-08-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0011_rename_umber_of_seats_single_bus_number_of_seats'),
        ('customer', '0010_remove_booking_seat_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_admin.seat'),
        ),
    ]
