# Generated by Django 4.0.6 on 2022-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_booking_seat_booking_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
