# Generated by Django 4.0.6 on 2022-08-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sub_route',
        ),
    ]
