# Generated by Django 4.0.6 on 2022-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_booking_sub_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='destnation',
            new_name='destination',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
