# Generated by Django 4.0.6 on 2022-08-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_rename_destnation_booking_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reserved_seats',
            field=models.IntegerField(null=True),
        ),
    ]
