# Generated by Django 4.0.6 on 2022-08-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_booking_reserved_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reserved_seats',
        ),
    ]
