# Generated by Django 4.0.6 on 2022-08-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_admin', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishPayment',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finishpymnt_booking', serialize=False, to='customer.booking')),
                ('paid_by', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('code', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishPaymentStatus',
            fields=[
                ('fnishpayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finishpayment_status', serialize=False, to='booker.finishpayment')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=55)),
                ('account_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.paymentmethod')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_admin.route')),
            ],
        ),
        migrations.AddField(
            model_name='finishpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.paymentinformantion'),
        ),
    ]
