# Generated by Django 4.1.1 on 2022-10-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subroute',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='system_admin.city'),
        ),
        migrations.AlterField(
            model_name='subroute',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.city'),
        ),
    ]
