# Generated by Django 4.0.6 on 2022-09-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0003_rename_admin_at_subrouteadmin_admin_at_city'),
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subroute',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_admin.route'),
        ),
    ]
