# Generated by Django 4.1.1 on 2022-09-20 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travaler_name', models.CharField(max_length=255, null=True)),
                ('traveler_contact', models.CharField(max_length=255, null=True)),
                ('seat_quantity', models.CharField(max_length=2, null=True)),
                ('status', models.CharField(default='Waiting', max_length=25)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sub_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booker.subroute')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
