# Generated by Django 4.1.2 on 2022-10-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travaler_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='traveler_contact',
        ),
    ]
