# Generated by Django 4.1.2 on 2022-10-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_busseat_seat_number'),
        ('booking', '0002_remove_booking_travaler_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('bus_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.busseat')),
            ],
        ),
    ]
