# Generated by Django 4.1 on 2022-08-29 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_city', models.CharField(max_length=255, null=True)),
                ('second_city', models.CharField(max_length=255, null=True)),
                ('via_cities', models.CharField(max_length=255, null=True)),
                ('travel_distance', models.IntegerField(null=True)),
                ('travel_aproximate_time', models.CharField(max_length=255, null=True)),
                ('single_seat_price', models.IntegerField(null=True)),
                ('travel_facilities', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubRouteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_at', models.CharField(max_length=255, null=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_admin.route')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_plate_number', models.IntegerField()),
                ('bus_number', models.CharField(max_length=200, null=True)),
                ('bus_type', models.CharField(max_length=200, null=True)),
                ('bus_detail', models.CharField(max_length=200, null=True)),
                ('number_of_seats', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bus_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.busbrand')),
            ],
        ),
    ]
