# Generated by Django 4.1 on 2022-08-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subroutebusadmin',
            name='subroute_bus',
            field=models.ManyToManyField(to='bus_admin.single_bus'),
        ),
    ]
