# Generated by Django 4.1 on 2022-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrouteadmin',
            name='admin_at',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
