# Generated by Django 4.0.6 on 2022-08-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='destnation',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start',
        ),
        migrations.RemoveField(
            model_name='route',
            name='travel_begin_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='via_cities',
        ),
        migrations.CreateModel(
            name='SubRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('start', models.CharField(max_length=255, null=True)),
                ('destnation', models.CharField(max_length=255, null=True)),
                ('via_cities', models.CharField(max_length=255, null=True)),
                ('travel_date', models.DateField()),
                ('travel_begin_time', models.TimeField()),
                ('main_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_admin.route')),
            ],
        ),
    ]
