# Generated by Django 4.1.1 on 2022-10-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
        ('bus_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.busbrand'),
        ),
    ]
