# Generated by Django 4.1 on 2022-08-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0002_alter_subrouteadmin_admin_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subrouteadmin',
            old_name='admin_at',
            new_name='admin_at_city',
        ),
    ]
