# Generated by Django 4.0.6 on 2022-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0002_remove_route_destnation_remove_route_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
