# Generated by Django 4.0.6 on 2022-08-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
        ('bus_admin', '0003_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ManyToManyField(null=True, related_name='route_bus', to='system_admin.bus'),
        ),
    ]
