# Generated by Django 4.0.6 on 2022-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0004_remove_route_bus_route_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.AddField(
            model_name='subroute',
            name='bus',
            field=models.ManyToManyField(null=True, related_name='single_route_bus', to='bus_admin.route'),
        ),
    ]
