# Generated by Django 4.0.6 on 2022-08-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
        ('bus_admin', '0006_alter_subroute_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_bus',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.bus'),
        ),
    ]
