# Generated by Django 4.0.6 on 2022-08-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
        ('bus_admin', '0007_single_bus_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ManyToManyField(null=True, related_name='route_bus', to='system_admin.bus'),
        ),
        migrations.AlterField(
            model_name='single_bus',
            name='bus_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='subroute',
            name='bus',
        ),
        migrations.AddField(
            model_name='subroute',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_route_bus', to='bus_admin.single_bus'),
        ),
    ]
