# Generated by Django 4.0.6 on 2022-08-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0008_route_bus_alter_single_bus_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subroute',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_admin.single_bus'),
        ),
    ]
