# Generated by Django 4.0.6 on 2022-08-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0010_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_bus',
            old_name='umber_of_seats',
            new_name='number_of_seats',
        ),
    ]
