# Generated by Django 4.0.6 on 2022-08-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_booking_sub_route'),
        ('bus_admin', '0011_rename_umber_of_seats_single_bus_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_begin_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='via_cities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_admin.single_bus'),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SubRoute',
        ),
    ]
