# Generated by Django 4.0.6 on 2022-08-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0012_route_destination_route_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='single_seat_price',
            field=models.IntegerField(null=True),
        ),
    ]
