# Generated by Django 4.0.6 on 2022-08-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_admin', '0013_route_single_seat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.CreateModel(
            name='SubRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_admin.single_bus')),
                ('main_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_admin.route')),
            ],
        ),
    ]
